version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - users-main
networks:
  users-main:
    driver: bridge
volumes:
  postgres-vol:
